export const SELECCIONAR_CLIENTE = 'SELECCIONAR_CLIENTE'
export const SELECCIONAR_PRODUCTO = 'SELECCIONAR_PRODUCTO'
export const CANTIDAD_DE_PRODUCTOS = 'CANTIDAD_DE_PRODUCTOS'
export const ACTUALIZAR_EL_TOTAL = 'ACTUALIZAR_EL_TOTAL'
